const { NODE_ENV, REACT_APP_PRODUCTION_BACKEND_URL, REACT_APP_DEVELOPMENT_BACKEND_URL } = process.env

const baseURL = NODE_ENV === 'production' ? REACT_APP_PRODUCTION_BACKEND_URL : REACT_APP_DEVELOPMENT_BACKEND_URL

export { baseURL }
